version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  target-branch: next
  versioning-strategy: widen
  ignore:
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  target-branch: next
  ignore:
  - dependency-name: wheel-gestures
    versions:
    - 2.2.4
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.0.1
    - 9.1.0
    - 9.1.1
  - dependency-name: react-use-gesture
    versions:
    - 9.0.0
    - 9.0.1
    - 9.0.2
    - 9.0.3
    - 9.0.4
    - 9.1.0
    - 9.1.1
    - 9.1.2
    - 9.1.3
  - dependency-name: "@reach/visually-hidden"
    versions:
    - 0.13.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
